version: "3.8"
services:
  utorrent:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ./downloads:/torrent/downloads
      - ./torrentfiles:/torrent/torrentfiles
    restart: unless-stopped
